### ISSUE TITLE
Works incorrect with live connection to multidimension SSAS

### ISSUE THREAD

**Issue by MichaelMelvin** [liprec/azurebi-docs#90]
*Start issue here*

I created several filters (HierarchySlicers) with staff/services etc. And several visualisations.
In PowerBI Desktop everything works well.
But when I open published report, there are troubles:
1. User checks one Item in some Slicer
2. Check mark appears, visualisations are updating
3. Check mark disappers (why?), visualisations had finished updating
And now hierarchy slicer (and whole report) behaves as if a checkmark is checked.
When I press the same item one more time, check mark appears and don't disappear.

How to fix it?

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=2380fb48-08d2-44bc-aaa2-2decb8eeed18
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/index.html

**Comment by liprec** [comment]
Hi @MichaelMelvin,

Sorry for the late response, but there should be a fix released that fixes this issue.
Can you confirm? Thanks

**Comment by CharlesWeyland** [comment]
Hello. I will check it on my OLAP report tomorrow. Now I just tested syncronization between synchronized h-slicers on different worksheets. And it works incorrect.
Example:
I choose an item in hierarchy slicer on the page 1, I see that charts on the page have changed. Then I go to the page 2, charts are changed on it too. But I don't see check mark in the appropriate checkbox on hierarchy slicer.
Source - Excel. All the data is imported to the report.

**Comment by CharlesWeyland** [comment]
I checked.
Still not working. Have you updated it in the powerbi store (appsource)? I've updated slicer in my report, but the version of the slicer has not changed - 2.0.22.
And the incorrect behavior still remains. I can make a video in case I need to.
