### ISSUE TITLE
Synced Slicer Filter applies to Pages but respective Selection is Unchecked

### ISSUE THREAD

**Issue by mariasroliveira1** [liprec/azurebi-docs#91]
Hi,

We have synced slicers across all Pages, so when I select my filter in the hierarchy slicer, this applies to all pages (works as it should), however the respective HSlicer selection is unchecked in every page but the one I have selected the filter, which makes difficult for the user to see what is the filter being applied. I know this component as worked fine before in this scenario but now something has changed. 

I also noticed that this still works fine if my filter works with the highest class on the hierarchy. For instance, I have Category and SubCategories inside each Category. When I apply my filter on Category, the respective selection will show as checked in other pages, but if I apply to SubCategory, this still filters all pages accordingly but I'm not able to see this selection checked in other pages.

Do you have any idea how to solve this issue?
Many thanks,
Maria

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=487cd175-be13-40df-a80e-aa1c7f531eb1
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer.html

**Comment by liprec** [comment]
Hi @mariasroliveira1,

Sorry for the late reaction, but if I am correctly there should be a fix released that solves this issue.
Can you confirm that the issue is not present anymore?

**Comment by simonbryant** [comment]
Hi @liprec 

I have the exact same issue, just update to the latest version of the slicer but the issue is still there. I updated by downloading the visual again and it asked if wanted to update, I assume that is all I needed to do?

FYI - using desktop version: 2.79.5768.1082 64-bit (March 2020)

Thanks,

Simon

**Comment by liprec** [comment]
Solved with the latest release in combination with the latest Power BI desktop
